import keyMirror from "keymirror";

export default keyMirror({
  AUTHENTICATE_USER_PENDING: null,
  AUTHENTICATE_USER_COMPLETE: null,
  AUTH_USER_LOGIN_PENDING: null,
  AUTH_USER_LOGIN_COMPLETE: null,
  AUTH_USER_REGISTER_PENDING: null,
  AUTH_USER_REGISTER_COMPLETE: null,
  AUTH_UPDATE_USER_PENDING: null,
  AUTH_UPDATE_USER_COMPLETE: null,
  AUTH_RESET_ERRORS: null,

  ROUTE_CHANGE_PENDING: null,
  ROUTE_CHANGE_COMPLETE: null,

  BOOK_CREATE_PENDING: null,
  BOOK_CREATE_COMPLETE: null,
  GET_BOOK_BY_ID_PENDING: null,
  GET_BOOK_BY_ID_COMPLETE: null,
  GET_GENRES_PENDING: null,
  GET_GENRES_COMPLETE: null,
  GET_INDEX_BOOKS_PENDING: null,
  GET_INDEX_BOOKS_COMPLETE: null,

  GET_USER_TRADES_PENDING: null,
  GET_USER_TRADES_COMPLETE: null,
  CREATE_TRADE_PENDING: null,
  CREATE_TRADE_COMPLETE: null,
  CANCEL_TRADE_PENDING: null,
  CANCEL_TRADE_COMPLETE: null,
  TRADE_RESET_ERRORS: null,

  GET_USER_PROFILE_PENDING: null,
  GET_USER_PROFILE_COMPLETE: null
});
