import keyMirror from 'keymirror';

export default keyMirror({
  AUTH_USER_LOGIN_PENDING: null,
  AUTH_USER_LOGIN_COMPLETE: null,
  AUTH_USER_REGISTER_PENDING: null,
  AUTH_USER_REGISTER_COMPLETE: null,
  AUTH_UPDATE_USER_PENDING: null,
  AUTH_UPDATE_USER_COMPLETE: null,

  ROUTE_CHANGE_PENDING: null,
  ROUTE_CHANGE_COMPLETE: null,

  BOOK_CREATE_PENDING: null,
  BOOK_CREATE_COMPLETE: null,
  GET_GENRES_PENDING: null,
  GET_GENRES_COMPLETE: null,
  GET_INDEX_BOOKS_PENDING: null,
  GET_INDEX_BOOKS_COMPLETE: null,
});
